spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudvendor?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

#JPA settings to connect with the database