spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudvendor?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: RestAPIProjectTC


#JPA settings to connect with the database


#Spring Security
#spring:
#    security:
#        oauth2:
#            client:
#                registration:
#                    google:
#                        client-id:
#                        client-secret:

